### ISSUE TITLE
not able to logout 

### ISSUE THREAD

**Issue by bhargavsk1077** [varunp2k/WhatsappAutomation#2]
tried adding the code to logout , i'm able to select the three dots which gives a menu ,
but the "Logout element" is not clickable  

- my addition to the code :
options = driver.find_element_by_xpath('//div[@title="Menu"]')
options.click()
logout = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[3]/div/header/div[2]/div/span/div[3]/span/div/ul/li[6]/div')
logout.click()
 
- the error :
```  
ElementClickInterceptedException: element click intercepted: Element <div class="_3zy-4 Sl-9e" role="button" title="...">Log out</div> is not clickable at point (295, 188). Other element would receive the click: <div class="_3zy-4 Sl-9e" role="button" title="...">Settings</div>
  (Session info: chrome=77.0.3865.90)
```

**Comment by Samyak2** [comment]
With reference to #3
You could do:

```
logout_xpath = '/html/body/div[1]/div/div/div[3]/div/header/div[2]/div/span/div[3]/span/div/ul/li[6]/div'
WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, logout_xpath)))
logout = driver.find_element_by_xpath(logout_xpath)
```
instead of giving an explicit sleep function.
This will wait till the element is clickable, for a maximum of 5 seconds (can be changed by changing the 2nd parameter of WebDriverWait). The element may not always be clickable after 2 seconds, so this is a safer option.
WebDriverWait could be used in (almost) all places where there are time.sleep() functions in this repo (would be a nice PR).

**Comment by varunp2k** [comment]
I will add these issues to Hacktober fest by tonight. Send PR after that
